# https://github.com/peaceiris/actions-mdbook
name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
          # mdbook-version: 'latest' / "0.4.25"
          # todo: Setup mdBook-Pagetoc

      - name: Setup mdBook-Pagetoc
        run: cargo install mdbook-pagetoc

      - name: Build Book
        run: mdbook build

      - name: Setup static-sitemap-cli
        run: npm install static-sitemap-cli

      - name: Generate SiteMap
        run: |
          cd book
          npx sscli --no-clean --base https://insultingpros.github.io/KFStory/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
